### ISSUE TITLE
Segfault if compile the .c source code

### ISSUE THREAD

**Issue by FrancescoLucarini** [Milo-D/house-of-gods#1] opened 2022-11-04 19:07 UTC
Hey Milo do you have any clue why the binary crashes despite the fact that gcc doesn't warn about anything?

**Comment by Milo-D** [comment] 2022-11-05 04:07
Hi Francesco,

could you send me the steps to reproduce this problem ? Thanks.

**Comment by FrancescoLucarini** [comment] 2022-11-05 07:40
gcc -o sandbox sabdbox.c

./sandbox

Segmentation Fault
![IMG20221105084038.jpg](https://user-images.githubusercontent.com/69625915/200109227-900037f9-62a6-446f-ac10-00556cbbf086.jpg)

**Comment by FrancescoLucarini** [comment] 2022-11-05 07:42
If I run
 ./patch.sh
./sandbox

./sandbox: /home/heap-nman/test/house_of_gods/Libc.so.6: version 'GLIBC_2.34' not found (required by ./sandbox)

**Comment by Milo-D** [comment] 2022-11-06 04:05
You need to compile the ```sandbox``` in an older environment. I was using a 17.10 Ubuntu VM in order to compile it. That's the reason why this repository comes with a prebuilt binary :)

Edit: patch the binary's runpath and interpreter with ```patch.sh``` after every recompilation of  ```sandbox``` in order to use custom ```libc``` and ```ld```.

**Comment by FrancescoLucarini** [comment] 2022-11-06 06:49
Oh ok thanks did you used any special flag on gcc or is actually like the mine the command?

**Comment by Milo-D** [comment] 2022-11-06 16:46
Nope, I did not use any special flags for compilation.

Feel free to close the issue if you have no further questions.

**Closed as completed** 2022-11-10 15:20 UTC
